### ISSUE TITLE
Not able to "rails g spree_recently_viewed:install"

### ISSUE THREAD

**Issue by tashi-179** [spree-contrib/spree_recently_viewed#49]
I am using spree version 4.1

When I try to `rails g spree_recently_viewed:install` it gives following errors. Can someone help me please?

```
/Users/tashi/.rvm/gems/ruby-2.6.5/gems/spree_core-4.1.5/app/models/spree/preferences/store.rb:9: warning: already initialized constant DB_EXCEPTIONS
/Users/tashi/.rvm/gems/ruby-2.6.5/gems/spree_core-4.1.5/app/models/spree/preferences/store.rb:9: warning: previous definition of DB_EXCEPTIONS was here
/Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:710:in `block (2 levels) in skip_callback': Before process_action callback :set_current_order has not been defined (ArgumentError)
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:706:in `each'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:706:in `block in skip_callback'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:628:in `block in __update_callbacks'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:626:in `reverse_each'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:626:in `__update_callbacks'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:705:in `skip_callback'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.2/lib/abstract_controller/callbacks.rb:215:in `block (3 levels) in <module:ClassMethods>'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.2/lib/abstract_controller/callbacks.rb:96:in `block in _insert_callbacks'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.2/lib/abstract_controller/callbacks.rb:95:in `each'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.2/lib/abstract_controller/callbacks.rb:95:in `_insert_callbacks'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.2/lib/abstract_controller/callbacks.rb:214:in `block (2 levels) in <module:ClassMethods>'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/bundler/gems/spree_recently_viewed-85f2e6870a7e/app/controllers/spree/products_controller_decorator.rb:5:in `prepended'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/bundler/gems/spree_recently_viewed-85f2e6870a7e/app/controllers/spree/products_controller_decorator.rb:28:in `prepend'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/bundler/gems/spree_recently_viewed-85f2e6870a7e/app/controllers/spree/products_controller_decorator.rb:28:in `<main>'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/bundler/gems/spree_recently_viewed-85f2e6870a7e/app/controllers/spree/products_controller_decorator.rb:1:in `<main>'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/bundler/gems/spree_recently_viewed-85f2e6870a7e/lib/spree_recently_viewed/engine.rb:16:in `block in activate'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/bundler/gems/spree_recently_viewed-85f2e6870a7e/lib/spree_recently_viewed/engine.rb:15:in `glob'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/bundler/gems/spree_recently_viewed-85f2e6870a7e/lib/spree_recently_viewed/engine.rb:15:in `activate'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:429:in `instance_exec'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:429:in `block in make_lambda'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:606:in `catch'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:606:in `block in default_terminator'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:202:in `block in halting'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:514:in `block in invoke_before'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:514:in `each'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:514:in `invoke_before'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:134:in `run_callbacks'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/reloader.rb:88:in `prepare!'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/application/finisher.rb:113:in `block in <module:Finisher>'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `run'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /Users/tashi/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        from /Users/tashi/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /Users/tashi/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /Users/tashi/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /Users/tashi/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each'
        from /Users/tashi/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `call'
        from /Users/tashi/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        from /Users/tashi/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        from /Users/tashi/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/application.rb:363:in `initialize!'
        from /Users/tashi/DragonCoder/btmade-app/config/environment.rb:7:in `<main>'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:106:in `preload'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:157:in `serve'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
        from /Users/tashi/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /Users/tashi/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/tashi/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
```

**Comment by mashhood-ahmad** [comment]
Facing the same issue. Following along.
